/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.Formatacao;
import apoio.Validacao;
import dao.GastosDAO;
import entidades.Gastos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */
public class IfrGastos extends javax.swing.JInternalFrame {
    int idGasto = 0;
    /**
     * Creates new form IfrPessoa
     */
    public IfrGastos() {
        initComponents();
        
        //Formatacao.formatarCpf(tfdValor);
        
        carregarDados();
    }
    
    private void carregarDados() {
        new GastosDAO().popularTabela(tblTema, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTema = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfdSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfdData = new javax.swing.JTextField();
        tfdDescricao = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tfdValor = new javax.swing.JFormattedTextField();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setTitle("Cadastro de gastos");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblTema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTema);

        jLabel5.setText("Filtrar:");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar gastos", jPanel1);

        jLabel1.setText("Data:");

        jLabel2.setText("Descrição");

        jLabel3.setText("Valor:");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfdValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdValorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdValor)
                            .addComponent(tfdDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(tfdData))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionar gasto", jPanel2);

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String valueData = tfdData.getText();
        String valueDescricao = tfdDescricao.getText();
        String valueValor = tfdValor.getText();
        
        if(valueData.isBlank()) {
            JOptionPane.showMessageDialog(this, "A data não pode ser vazia");
            tfdData.requestFocus();
            return;
        }
        
        if(valueDescricao.isBlank()) {
            JOptionPane.showMessageDialog(this, "A descrição do gasto não pode ser vazia");
            tfdDescricao.requestFocus();
            return;
        }
        
        if(valueValor.isBlank()) {
            JOptionPane.showMessageDialog(this, "O valor não pode ser vazio");
            tfdValor.requestFocus();
            return;
        }
        
        
        Gastos gasto = new Gastos();
        gasto.setId(idGasto);
        gasto.setData(valueData);
        gasto.setDescricao_gasto(valueDescricao);
        gasto.setValor(Double.parseDouble(valueValor));
        
        GastosDAO gastoDAO = new GastosDAO();
        
        if(idGasto == 0) {
            if(gastoDAO.salvar(gasto) == null) {
                tfdData.setText("");
                tfdDescricao.setText("");
                tfdValor.setText("");

                JOptionPane.showMessageDialog(this, "Gasto adicionado com sucesso");

                carregarDados();
                tfdData.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do gasto");
            }
        } else {
            if(gastoDAO.atualizar(gasto) == null) {
                tfdData.setText("");
                tfdDescricao.setText("");
                tfdValor.setText("");

                JOptionPane.showMessageDialog(this, "Gasto atualizado com sucesso");

                carregarDados();
                tfdData.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do gasto");
            }
        }
        
        idGasto = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new GastosDAO().popularTabela(tblTema, tfdSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        String idTabela = String.valueOf(tblTema.getValueAt(tblTema.getSelectedRow(), 0));
        
        idGasto = Integer.parseInt(idTabela);
        Gastos gasto = new GastosDAO().consultarId(idGasto);
        
        if(gasto != null) {
            jTabbedPane1.setSelectedIndex(1);
            
            tfdData.setText(gasto.getData());
            tfdDescricao.setText(gasto.getDescricao_gasto());
            tfdValor.setText(gasto.getValor().toString());
            
            tfdData.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do gasto não encontrado");
        }
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        String idTabela = String.valueOf(tblTema.getValueAt(tblTema.getSelectedRow(), 0));
        
        idGasto = Integer.parseInt(idTabela);
        String cliente = new GastosDAO().excluir(idGasto);
        
        if(cliente == null) {
            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso");
            
            carregarDados();
        } else {
           JOptionPane.showMessageDialog(this, "Problemas ao excluir o registro");
        }
        
        idGasto = 0;
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void tfdValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdValorFocusGained

    }//GEN-LAST:event_tfdValorFocusGained

    private void tfdValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdValorFocusLost
        //if(!Validacao.validarCPF(Formatacao.removerFormatacao(tfdValor.getText()))) {
          //  tfdValor.setBackground(Color.red);
        //} else {
          //  tfdValor.setBackground(Color.WHITE);
        //}
    }//GEN-LAST:event_tfdValorFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblTema;
    private javax.swing.JTextField tfdData;
    private javax.swing.JTextField tfdDescricao;
    private javax.swing.JTextField tfdSearch;
    private javax.swing.JFormattedTextField tfdValor;
    // End of variables declaration//GEN-END:variables
}
