/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.Formatacao;
import apoio.Validacao;
import dao.TemaGenericoDAO;
import entidades.TemaGenerico;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */
public class IfrTema extends javax.swing.JInternalFrame {
    int idCliente = 0;
    /**
     * Creates new form IfrPessoa
     */
    public IfrTema() {
        initComponents();
        
        Formatacao.formatarCpf(jFormattedTextCPF);
        Formatacao.formatarTelefone(textFieldFormatedTelefone);
        
        carregarDados();
    }
    
    private void carregarDados() {
        new TemaGenericoDAO().popularTabela(tblTema, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTema = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfdSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdNomeCliente = new javax.swing.JTextField();
        tfdEmailCliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jFormattedTextCPF = new javax.swing.JFormattedTextField();
        textFieldFormatedTelefone = new javax.swing.JFormattedTextField();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setTitle("Cadastro de ${tema}");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblTema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTema);

        jLabel5.setText("Filtrar:");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar tema", jPanel1);

        jLabel1.setText("Nome:");

        jLabel2.setText("Email:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Telefone:");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jFormattedTextCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextCPFFocusLost(evt);
            }
        });

        textFieldFormatedTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldFormatedTelefoneFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdEmailCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                            .addComponent(tfdNomeCliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldFormatedTelefone)
                            .addComponent(jFormattedTextCPF))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfdEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldFormatedTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionar tema", jPanel2);

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String valueNome = tfdNomeCliente.getText();
        String valueEmail = tfdEmailCliente.getText();
        String valueCpf = jFormattedTextCPF.getText();
        String valueTelefone = textFieldFormatedTelefone.getText();
        
        if(valueNome.isBlank()) {
            JOptionPane.showMessageDialog(this, "O nome não pode ser vazio");
            tfdNomeCliente.requestFocus();
            return;
        }
        
        if(valueEmail.isBlank()) {
            JOptionPane.showMessageDialog(this, "A descrição do endereço de email não pode ser vazia");
            tfdEmailCliente.requestFocus();
            return;
        }
        
        if(valueCpf.isBlank()) {
            JOptionPane.showMessageDialog(this, "O CPF não pode ser vazio");
            jFormattedTextCPF.requestFocus();
            return;
        }
        
        if(valueTelefone.isBlank()) {
            JOptionPane.showMessageDialog(this, "O telefone não pode ser vazio");
            textFieldFormatedTelefone.requestFocus();
            return;
        }
        
        TemaGenerico cliente = new TemaGenerico();
        cliente.setId(idCliente);
        cliente.setNome(valueNome);
        cliente.setEmail(valueEmail);
        cliente.setCpf(valueCpf);
        cliente.setTelefone(valueTelefone);
        
        TemaGenericoDAO clienteDAO = new TemaGenericoDAO();
        
        if(idCliente == 0) {
            if(clienteDAO.salvar(cliente) == null) {
                tfdNomeCliente.setText("");
                tfdEmailCliente.setText("");
                jFormattedTextCPF.setText("");
                textFieldFormatedTelefone.setText("");

                JOptionPane.showMessageDialog(this, "Cliente adicionado com sucesso");

                carregarDados();
                tfdNomeCliente.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do cliente");
            }
        } else {
            if(clienteDAO.atualizar(cliente) == null) {
                tfdNomeCliente.setText("");
                tfdEmailCliente.setText("");
                jFormattedTextCPF.setText("");
                textFieldFormatedTelefone.setText("");

                JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso");

                carregarDados();
                tfdNomeCliente.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do cliente");
            }
        }
        
        idCliente = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new TemaGenericoDAO().popularTabela(tblTema, tfdSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        String idTabela = String.valueOf(tblTema.getValueAt(tblTema.getSelectedRow(), 0));
        
        idCliente = Integer.parseInt(idTabela);
        TemaGenerico cliente = new TemaGenericoDAO().consultarId(idCliente);
        
        if(cliente != null) {
            jTabbedPane1.setSelectedIndex(1);
            
            tfdNomeCliente.setText(cliente.getNome());
            tfdEmailCliente.setText(cliente.getEmail());
            jFormattedTextCPF.setText(cliente.getCpf());
            textFieldFormatedTelefone.setText(cliente.getTelefone());
            
            tfdNomeCliente.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do cliente não encontrado");
        }
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        String idTabela = String.valueOf(tblTema.getValueAt(tblTema.getSelectedRow(), 0));
        
        idCliente = Integer.parseInt(idTabela);
        String cliente = new TemaGenericoDAO().excluir(idCliente);
        
        if(cliente == null) {
            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso");
            
            carregarDados();
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir o registro");
        }
        
        idCliente = 0;
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void jFormattedTextCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextCPFFocusGained

    }//GEN-LAST:event_jFormattedTextCPFFocusGained

    private void jFormattedTextCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextCPFFocusLost
        if(!Validacao.validarCPF(Formatacao.removerFormatacao(jFormattedTextCPF.getText()))) {
            jFormattedTextCPF.setBackground(Color.red);
        } else {
            jFormattedTextCPF.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jFormattedTextCPFFocusLost

    private void textFieldFormatedTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFormatedTelefoneFocusLost
        if(!Validacao.validarTelefone(textFieldFormatedTelefone)) {
            textFieldFormatedTelefone.setBackground(Color.red);
        } else {
            textFieldFormatedTelefone.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_textFieldFormatedTelefoneFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblTema;
    private javax.swing.JFormattedTextField textFieldFormatedTelefone;
    private javax.swing.JTextField tfdEmailCliente;
    private javax.swing.JTextField tfdNomeCliente;
    private javax.swing.JTextField tfdSearch;
    // End of variables declaration//GEN-END:variables
}
